PowerC<- read.csv("household_power_consumption.txt", header = TRUE, sep=";", na.strings="?", nrows=2075259)
pcsub<-subset(PowerC, PowerC$Date %in% c("1/2/2007","2/2/2007"))
pcsub$Date <- as.Date(pcsub$Date, format="%d/%m/%Y")
pcsub$DateTime <- as.POSIXct(paste(pcsub$Date, pcsub$Time))
png("plot4.png",width = 480, height=480)
par(mfrow=c(2,2))
plot(pcsub$DateTime, pcsub$Global_active_power, xlab='', ylab = "Global Active Power", type = "l")
plot(pcsub$DateTime,pcsub$Voltage,xlab= 'datetime', ylab='Voltage', type='l')
plot(pcsub$DateTime, pcsub$Sub_metering_1, xlab='', ylab = "Energy sub metering", type = "l")
lines(pcsub$DateTime, pcsub$Sub_metering_3, type = "l", col ="blue")
lines(pcsub$DateTime, pcsub$Sub_metering_2, type = "l", col ="red")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lwd=c(1,1,1),col=c("black", "red", "blue"),cex = 0.9, bty = "n")
plot(pcsub$DateTime,pcsub$Global_reactive_power,xlab= 'datetime', ylab='Global_reactive_power', type='l')
dev.off()


